runtime: go111

env: standard
service: default
instance_class: F1
handlers:
  - url: /queue/.*
    script: auto
    login: admin

  - url: '/.*'
    script: auto

env_variables:
  PROJECT_ID: <YOUR_CDN_PROJECT_ID>
  URL_MAP: <YOUR_CDN_URL_MAP>
  # example DOMAIN_VERIFICATION: googlede741431784b6b76.html
  DOMAIN_VERIFICATION: <GOOGLE_VERIFICATION>
